import fs from "node:fs";
import path from "node:path";
import type { Vm0007RuleLike } from "@/lib/preverif/vm0007EvidenceContracts";

export type Vm0007RuleFixture = Vm0007RuleLike;

export const VM0007_SYNCED_RULES: readonly Vm0007RuleFixture[] = [
  { id: "R-1-0001", summary: "REDD forest land definition", type: "eligibility" },
  { id: "R-1-0002", summary: "REDD baseline deforestation category", type: "eligibility" },
  { id: "R-1-0003", summary: "AUDef agent criteria", type: "eligibility" },
  { id: "R-1-0004", summary: "APDef legal authorization", type: "eligibility" },
  { id: "R-1-0005", summary: "WRC water table prohibition", type: "eligibility" },
  { id: "R-1-0006", summary: "WRC organic soil burning prohibition", type: "eligibility" },
  { id: "R-1-0007", summary: "WRC nitrogen fertilizer prohibition", type: "eligibility" },
  { id: "R-1-0008", summary: "WRC hydrological connectivity check", type: "eligibility" },
  { id: "R-1-0009", summary: "RWE prior land use requirement", type: "eligibility" },
  { id: "R-1-0010", summary: "Peatland VCS definition", type: "eligibility" },
  { id: "R-1-0011", summary: "Tidal wetland restoration activities", type: "eligibility" },
  { id: "R-1-0012", summary: "CIW tidal wetland conservation activities", type: "eligibility" },
  { id: "R-1-0013", summary: "AUWD agent criteria", type: "eligibility" },
  { id: "R-1-0014", summary: "IFM and ARR exclusion", type: "eligibility" },
  { id: "R-1-0015", summary: "Leakage prevention activity restrictions", type: "eligibility" },
  { id: "R-2-0001", summary: "Geographic boundary definition", type: "eligibility" },
  { id: "R-2-0002", summary: "No spatial overlap between baselines", type: "eligibility" },
  { id: "R-2-0003", summary: "Exclusion of land in other GHG programs", type: "monitoring" },
  { id: "R-2-0004", summary: "REDD reference region definition", type: "eligibility" },
  { id: "R-2-0005", summary: "REDD proxy area definition", type: "eligibility" },
  { id: "R-2-0006", summary: "Stratification requirement", type: "eligibility" },
  { id: "R-2-0007", summary: "Carbon pool selection per activity type", type: "eligibility" },
  { id: "R-2-0008", summary: "REDD mandatory carbon pools", type: "calc" },
  { id: "R-2-0009", summary: "WRC carbon pools", type: "calc" },
  { id: "R-2-0010", summary: "REDD GHG source identification", type: "eligibility" },
  { id: "R-2-0011", summary: "WRC GHG source identification", type: "eligibility" },
  { id: "R-2-0012", summary: "Consistency rule: baseline-project source matching", type: "eligibility" },
  { id: "R-2-0013", summary: "Historical reference period", type: "eligibility" },
  { id: "R-2-0014", summary: "Crediting period duration", type: "eligibility" },
  { id: "R-2-0015", summary: "WRC 100-year SOC difference requirement", type: "calc" },
  { id: "R-2-0016", summary: "Tidal wetland sea-level rise boundary", type: "eligibility" },
  { id: "R-3-0001", summary: "Baseline scenario determination via VT0001", type: "calc" },
  { id: "R-3-0002", summary: "Minimum alternative scenario list", type: "eligibility" },
  { id: "R-3-0003", summary: "Barrier analysis baseline selection", type: "calc" },
  { id: "R-3-0004", summary: "Investment analysis baseline selection", type: "calc" },
  { id: "R-3-0005", summary: "REDD baseline modules", type: "calc" },
  { id: "R-3-0006", summary: "WRC baseline modules", type: "calc" },
  { id: "R-3-0007", summary: "Baseline reassessment frequency", type: "monitoring" },
  { id: "R-3-0008", summary: "JNR data use", type: "calc" },
  { id: "R-4-0001", summary: "VT0001 additionality requirement", type: "eligibility" },
  { id: "R-4-0002", summary: "Tidal wetland additionality method", type: "eligibility" },
  { id: "R-5-0001", summary: "REDD net emission reduction equation", type: "equation" },
  { id: "R-5-0002", summary: "WRC net emission reduction equation", type: "equation" },
  { id: "R-5-0003", summary: "REDD leakage components", type: "calc" },
  { id: "R-5-0004", summary: "WRC leakage components", type: "calc" },
  { id: "R-5-0005", summary: "Buffer pool contribution calculation", type: "calc" },
  { id: "R-5-0006", summary: "Uncertainty adjustment", type: "uncertainty" },
  { id: "R-5-0007", summary: "VCU calculation", type: "equation" },
  { id: "R-5-0008", summary: "Carbon pool modules for REDD", type: "calc" },
  { id: "R-5-0009", summary: "Project emissions modules", type: "calc" },
  { id: "R-6-0001", summary: "Monitoring plan four tasks", type: "monitoring" },
  { id: "R-6-0002", summary: "Monitoring plan content requirements", type: "monitoring" },
  { id: "R-6-0003", summary: "Geographic position recording", type: "monitoring" },
  { id: "R-6-0004", summary: "SOP and QA/QC requirements", type: "monitoring" },
  { id: "R-6-0005", summary: "REDD forest cover monitoring", type: "monitoring" },
  { id: "R-6-0006", summary: "WRC compliance monitoring", type: "monitoring" },
  { id: "R-6-0007", summary: "Expert judgment documentation", type: "monitoring" },
  { id: "R-6-0008", summary: "Uncertainty reduction requirements", type: "uncertainty" },
];

export function readQuickCheckFixtureText(filename: string): string {
  return fs.readFileSync(path.join(process.cwd(), "tests/fixtures/quick-check", filename), "utf8");
}
