import fs from "fs";
import path from "path";
import { describe, expect, it } from "@jest/globals";
import {
  classifyQuickCheckDocument,
  quickCheckDocumentClassLabel,
  type QuickCheckDocumentClass,
} from "@/lib/documentClassification";

type ClassificationFixture = {
  fileName: string;
  fixturePath: string;
  expectedClass: QuickCheckDocumentClass;
};

const FIXTURES: ClassificationFixture[] = [
  {
    fileName: "VALID_REP_1530_31MAY2016.pdf",
    fixturePath: "tests/fixtures/quick-check/vichada-validation-report-extracted.txt",
    expectedClass: "validation_report",
  },
  {
    fileName: "VERRA-Verification-Report_2016-2021.pdf",
    fixturePath: "tests/fixtures/quick-check/generation-forest-verification-extracted.txt",
    expectedClass: "verification_report",
  },
  {
    fileName: "PLUM a.pdf",
    fixturePath: "tests/fixtures/quick-check/a-pdf-extracted.txt",
    expectedClass: "project_description_pdd",
  },
  {
    fileName: "PD_REDD_v1_130.pdf",
    fixturePath: "tests/fixtures/quick-check/pd_redd_v1_130-extracted.txt",
    expectedClass: "project_description_pdd",
  },
  {
    fileName: "PROJ_DESC_1382_04APR2015.pdf",
    fixturePath: "tests/fixtures/quick-check/proj-desc-1382-extracted.txt",
    expectedClass: "project_description_pdd",
  },
];

describe("quick check document classification", () => {
  for (const fixture of FIXTURES) {
    it(`classifies ${fixture.fileName} as ${fixture.expectedClass}`, () => {
      const rawText = fs.readFileSync(path.join(process.cwd(), fixture.fixturePath), "utf-8");
      const result = classifyQuickCheckDocument({
        fileName: fixture.fileName,
        mime: "application/pdf",
        rawText,
      });

      expect(result.documentClass).toBe(fixture.expectedClass);
      expect(result.evidence.length).toBeGreaterThan(0);
      expect(result.secondaryCandidates.length).toBeGreaterThanOrEqual(0);
      expect(result.confidence).toBeGreaterThan(0.45);
      expect(quickCheckDocumentClassLabel(result.documentClass)).toBeTruthy();
    });
  }

  it("returns provenance-backed secondary candidates", () => {
    const rawText = fs.readFileSync(
      path.join(process.cwd(), "tests/fixtures/quick-check/generation-forest-verification-extracted.txt"),
      "utf-8",
    );
    const result = classifyQuickCheckDocument({
      fileName: "VERRA-Verification-Report_2016-2021.pdf",
      mime: "application/pdf",
      rawText,
    });

    expect(result.documentClass).toBe("verification_report");
    expect(result.evidence.some((item) => /filename|page 1 header|repeated header/i.test(item))).toBe(true);
    expect(result.secondaryCandidates.every((candidate) => candidate.documentClass !== result.documentClass)).toBe(true);
    expect(result.secondaryCandidates.every((candidate) => Array.isArray(candidate.evidence))).toBe(true);
  });

  it("prefers a repeated OCR-fused monitoring title over generic project-description section names", () => {
    const rawText = [
      "MONITORINGREPORT: CCBVersion 3 ,VCSVersion3 CCB v3. 0,VCSv3.4 1 GROUPEDPROJECTFOR COMMERCIAL FOREST PLANTATIONSINITIATIVES IN THE DEPARTMENTOFVICHADA",
      "MonitoringP eriod ofthis Report 01 A ugust 2011 12 December 2 020",
      "MONITORINGREPORT: CCBVersion 3 ,VCSVersion3 CCB v3. 0,VCSv3.4 3 Tabl e of C ontents",
      "2.1 Project Description",
      "3.1 MonitoringGHGEmiss ionReductionsandRemovals",
      "6 ADDITIONALPROJECTIMPLEMENTATION INFORMATION",
      "MONITORINGREPORT: CCBVersion 3 ,VCSVersion3",
    ].join(" ");

    const result = classifyQuickCheckDocument({
      fileName: "CCB_MON_REP_ENG-1530_01AUG2011_12DEC2020.pdf",
      mime: "application/pdf",
      rawText,
    });

    expect(result.documentClass).toBe("monitoring_report");
    expect(result.evidence.some((item) => /page 1 title: "MONITORINGREPORT"/i.test(item))).toBe(true);
  });

  it("treats legal definition documents as registry/public records even when they define report terms", () => {
    const rawText = [
      "VCS ISSUANCE DEED OF REPRESENTATION",
      "THIS DEED OF REPRESENTATION is made on 09-July-2021.",
      "\"MonitoringReport\" means the document that records data to allow the assessment of the Reductions generated by the Project.",
      "\"ProjectDescription\" means the document that describes the Project's Reduction activities.",
      "\"VerificationPeriod\" means the time period specified in the Verification Report.",
      "\"VerificationReport\" means the written report of the verification covering the Reductions generated by the Project during the VerificationPeriod.",
      "The Verra ProjectDatabase provides public access.",
    ].join(" ");

    const result = classifyQuickCheckDocument({
      fileName: "ISS_REP_1530_09JUL2021.pdf",
      mime: "application/pdf",
      rawText,
    });

    expect(result.documentClass).toBe("registry_or_public_record");
    expect(result.evidence.some((item) => /deed/i.test(item))).toBe(true);
    expect(result.evidence.every((item) => !/VerificationReport/i.test(item))).toBe(true);
  });
});
