"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { loadVm0007EvidenceMapDraft } from "@/lib/preverif/vm0007EvidenceMapDraftStore";
import type { Vm0007EvidenceMapDraftPackage } from "@/lib/preverif/vm0007EvidenceMapDraft";

export default function Vm0007EvidenceMapDraftPage({ auditId }: { auditId: string }) {
  const [pkg, setPkg] = useState<Vm0007EvidenceMapDraftPackage | null>(null);
  useEffect(() => setPkg(loadVm0007EvidenceMapDraft(auditId)), [auditId]);
  if (!pkg) return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-4xl rounded-2xl border border-amber-200 bg-white p-6 text-amber-900">Evidence Map is blocked or not available for this audit. Only a successful VM0007 v1.8 audit can create the complete 58-rule draft.</div></main>;
  const counts = pkg.rows.reduce<Record<string, number>>((all, row) => ({ ...all, [row.rawAuditStatus]: (all[row.rawAuditStatus] ?? 0) + 1 }), {});
  return <main className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-7xl"><div className="mb-5 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-sm font-semibold text-amber-950">Machine-proposed Evidence Map. These rows have not been reviewer-finalized and do not constitute formal VVB findings.</div><section className="mb-5 rounded-2xl border border-slate-200 bg-white p-5"><h1 className="text-xl font-semibold text-slate-950">VM0007 v1.8 Evidence Map</h1><p className="mt-2 text-sm text-slate-600">Source: {pkg.sourceDocument.documentName || pkg.sourceDocument.documentId} · Audit ID: {pkg.auditId} · {pkg.rows.length} rows</p><p className="mt-2 text-sm text-slate-600">Source audit status: {Object.entries(counts).map(([status, count]) => `${status} ${count}`).join(" · ")}</p></section><div className="space-y-4">{pkg.rows.map((row) => <article key={row.rowId} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="font-semibold text-slate-950">{row.ruleReference} · {row.ruleTitle}</h2><span className="rounded-full border border-slate-300 px-2 py-1 text-xs font-semibold">{row.rawAuditStatus}</span></div><p className="mt-2 text-sm text-slate-600">Proposed evidence: {row.proposedEvidenceStatus} · Applicability: {row.proposedApplicability} · Confidence: {row.confidence}</p><dl className="mt-3 grid gap-3 text-sm md:grid-cols-2"><div><dt className="font-semibold text-slate-700">Accepted / candidate evidence</dt><dd className="mt-1 text-slate-600">{row.proposedAcceptedEvidence?.quote || "None proposed"}</dd></div><div><dt className="font-semibold text-slate-700">Rejected / uncertain evidence</dt><dd className="mt-1 text-slate-600">{row.proposedRejectedEvidence ? `${row.proposedRejectedEvidence.quote} — ${row.proposedRejectedEvidence.reason}` : "None proposed"}</dd></div><div><dt className="font-semibold text-slate-700">Quote / location</dt><dd className="mt-1 text-slate-600">{row.quote || "No quote"} · page {row.page ?? "—"} · {row.section || "No section"}</dd></div><div><dt className="font-semibold text-slate-700">Assessment / client action</dt><dd className="mt-1 text-slate-600">{row.assessmentReason} {row.clientAction}</dd></div><div className="md:col-span-2"><dt className="font-semibold text-slate-700">Provenance</dt><dd className="mt-1 text-slate-600">{row.provenance ? `${row.provenance.docId} · ${row.provenance.spanId} · ${row.provenance.sectionHeading || "No section"}` : "No provenance proposed"}</dd></div></dl></article>)}</div><Link className="mt-6 inline-block text-sm underline" href={`/internal/reports/vm0007-gap/${encodeURIComponent(auditId)}`}>View existing VM0007 gap report</Link></div></main>;
}
