import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { buildVm0007Rc2Baseline, serializeVm0007Rc2Baseline } from "@/lib/preverif/vm0007Rc2Baseline";
import { buildVm0007Rc3Diagnostic, classifyRc3MissCause, serializeVm0007Rc3Diagnostic, validateVm0007Rc3Diagnostic } from "@/lib/preverif/vm0007Rc3Diagnostic";
import { evaluateVm0007EvidenceBenchmark } from "@/lib/preverif/vm0007EvidenceBenchmark";

const root = process.cwd(); const dir = path.join(root, "tests/fixtures/preverif/marcondes-vm0007-v18-evidence-map"); const artifacts = path.join(root, "docs/roadmaps/interactive-evidence-review-mvp/rc/rc3");
const read = (file: string) => JSON.parse(fs.readFileSync(file, "utf8")); const digest = (file: string) => crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
function input() { const machine = read(path.join(dir, "machine-proposal.json")); const reviewed = read(path.join(dir, "gold.rc2-rc3.json")); const registry = read(path.join(root, "public/methodologies/Verra/AFOLU/VM0007/v1-8/rules.json")); const reconciliation = read(path.join(dir, "mismatch-reconciliation.json")); const baselinePath = path.join(artifacts, "RC2_BASELINE.json"); const baseline = buildVm0007Rc2Baseline({ machineRows: machine.rows, reviewedRows: reviewed.rows, expectedStableRuleIds: registry.rules.map((rule: { stable_id: string }) => rule.stable_id), reconciliationRows: reconciliation.rows, fixtureIdentity: { machineProposal: { path: path.relative(root, path.join(dir, "machine-proposal.json")), sha256: digest(path.join(dir, "machine-proposal.json")) }, reviewedTruth: { path: path.relative(root, path.join(dir, "gold.json")), sha256: digest(path.join(dir, "gold.rc2-rc3.json")) }, stableRuleRegistry: { path: path.relative(root, path.join(root, "public/methodologies/Verra/AFOLU/VM0007/v1-8/rules.json")), sha256: digest(path.join(root, "public/methodologies/Verra/AFOLU/VM0007/v1-8/rules.json")) }, reconciliation: { path: path.relative(root, path.join(dir, "mismatch-reconciliation.json")), sha256: digest(path.join(dir, "mismatch-reconciliation.json")) } } }); const extraction = read(path.join(dir, "raw-document-extraction.json")); return { machine, reviewed, baseline, extraction, baselinePath, benchmark: evaluateVm0007EvidenceBenchmark({ machineRows: machine.rows, reviewedRows: reviewed.rows, expectedStableRuleIds: baseline.stableRuleIds }) }; }
let diagnosticCache: ReturnType<typeof buildVm0007Rc3Diagnostic> | null = null;
function diagnostic() { if (diagnosticCache) return diagnosticCache; const x = input(); const artifact = read(path.join(artifacts, "RC3_DIAGNOSTIC.json")); const traces = new Map<string, any>(); for (const event of artifact.events) { const current = traces.get(event.stableRuleId) ?? { stableId: event.stableRuleId, retrievalCandidates: [], postFilterCandidates: [], selectedCandidates: [], cutoffPosition: event.detail.cutoffPosition }; current.retrievalCandidates.push(...event.detail.retrievalCandidates); current.postFilterCandidates.push(...event.detail.postFilterCandidates); current.selectedCandidates.push(...event.detail.selectedCandidates); traces.set(event.stableRuleId, current); } diagnosticCache = buildVm0007Rc3Diagnostic({ benchmark: x.benchmark, machineRows: x.machine.rows, reviewedRows: x.reviewed.rows, diagnosticTrace: [...traces.values()], sourceCorpus: { documentId: "quick-check-review-question", documentSha256: x.machine.sourceDocument.contentSha256, extractionPath: path.relative(root, path.join(dir, "raw-document-extraction.json")), text: x.extraction.text }, baseline: { artifactPath: path.relative(root, x.baselinePath), artifactSha256: digest(x.baselinePath) } }); return diagnosticCache; }

describe("RC3-1 accepted-evidence diagnostic contract", () => {
  it("keeps the frozen RC2 artifact reproducible and unchanged", () => { const x = input(); expect(serializeVm0007Rc2Baseline(x.baseline)).toBe(fs.readFileSync(x.baselinePath, "utf8")); expect(digest(x.baselinePath)).toBe("15c0497eae4d128c3828fe951e204ff46db0aa282b711877b7556ecabe8787cf"); });
  it("classifies all 95 events exactly once with the unchanged 58 false-support count", () => { const x = diagnostic(); expect(x.totals.categoryCounts).toEqual({ never_retrieved: 13, retrieved_but_filtered: 35, ranked_below_cutoff: 0, selected_but_match_failed: 47, unresolved_insufficient_trace: 0 }); expect(Object.values(x.totals.categoryCounts).reduce((sum, count) => sum + count, 0)).toBe(95); expect(new Set(x.events.map((event) => event.eventId)).size).toBe(95); expect(x.events).toHaveLength(95); expect(x.baseline.acceptedEvidenceFalseSupport).toBe(58); });
  it("emits deterministic output and preserves reviewed truth, fixtures, and proposal metrics", () => { const before = ["gold.rc2-rc3.json", "machine-proposal.json", "raw-document-extraction.json"].map((file) => fs.readFileSync(path.join(dir, file))); const x = diagnostic(); const first = serializeVm0007Rc3Diagnostic(x); const second = serializeVm0007Rc3Diagnostic(diagnostic()); expect(second).toBe(first); expect(x.baseline.acceptedEvidenceFalseSupport).toBe(58); expect(x.baseline.acceptedEvidenceMissed).toBe(95); expect(["gold.rc2-rc3.json", "machine-proposal.json", "raw-document-extraction.json"].map((file) => fs.readFileSync(path.join(dir, file)))).toEqual(before); });
  it("fails duplicate or omitted event validation", () => { const x = diagnostic(); expect(() => validateVm0007Rc3Diagnostic({ ...x, events: x.events.slice(0, -1), totals: { ...x.totals, classified: 94 } })).toThrow("does not equal 95"); expect(() => validateVm0007Rc3Diagnostic({ ...x, events: [...x.events.slice(0, -1), x.events[0]] })).toThrow("Duplicate RC3 diagnostic event ID"); });
  it("proves every classification branch with synthetic traces", () => { const candidate = (quote: string) => ({ spanId: quote, quote, page: 1, score: 10, evidenceType: "project_specific_implementation" as const, rejectionReason: null }); const base = { stableId: "rule", retrievalCandidates: [], postFilterCandidates: [], selectedCandidates: [], cutoffPosition: 6 }; expect(classifyRc3MissCause("target", undefined)).toBe("unresolved_insufficient_trace"); expect(classifyRc3MissCause("target", { ...base, retrievalCandidates: [candidate("other")] })).toBe("never_retrieved"); expect(classifyRc3MissCause("target", { ...base, retrievalCandidates: [candidate("target")], postFilterCandidates: [] })).toBe("retrieved_but_filtered"); expect(classifyRc3MissCause("target", { ...base, retrievalCandidates: [candidate("target")], postFilterCandidates: [candidate("target")], selectedCandidates: [] })).toBe("ranked_below_cutoff"); expect(classifyRc3MissCause("target", { ...base, retrievalCandidates: [candidate("target")], postFilterCandidates: [candidate("target")], selectedCandidates: [candidate("target")] })).toBe("selected_but_match_failed"); });
});
