name: Next.js tests

on:
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'package-lock.json'
      - 'vitest.config.ts'
      - '.github/workflows/next-test.yml'
      - 'tsconfig.json'
  push:
    branches:
      - main

concurrency:
  group: next-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd7195c27dd4afd2697dcd865986b253859d94

      - name: Use Node.js 20
        uses: actions/setup-node@60edb5dd254dff258ba7707d30f08259f4003e8f
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          NEXT_PUBLIC_ENABLE_AUDIT: 'true'
        run: npm run test
